// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGkayY0W_IKIs2ckfpUxrB0t9yCbx8E70',
    appId: '1:407630001413:web:2991bab631a13487d7336c',
    messagingSenderId: '407630001413',
    projectId: 'cocktail-45ff1',
    authDomain: 'cocktail-45ff1.firebaseapp.com',
    storageBucket: 'cocktail-45ff1.appspot.com',
    measurementId: 'G-X831Z54X5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5xxqZ13zYIRzRPh7k5VlfeV5nx8bTXIM',
    appId: '1:407630001413:android:a2e9051099fba5e3d7336c',
    messagingSenderId: '407630001413',
    projectId: 'cocktail-45ff1',
    storageBucket: 'cocktail-45ff1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl3XSX_RW1-GLNVSCp6dbLZL07I3Agbzk',
    appId: '1:407630001413:ios:b47b1977b9caf7f5d7336c',
    messagingSenderId: '407630001413',
    projectId: 'cocktail-45ff1',
    storageBucket: 'cocktail-45ff1.appspot.com',
    iosBundleId: 'com.example.cocktail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl3XSX_RW1-GLNVSCp6dbLZL07I3Agbzk',
    appId: '1:407630001413:ios:5caacf9d286cd158d7336c',
    messagingSenderId: '407630001413',
    projectId: 'cocktail-45ff1',
    storageBucket: 'cocktail-45ff1.appspot.com',
    iosBundleId: 'com.example.cocktail.RunnerTests',
  );
}
